fix main

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -61,19 +61,8 @@ pipeline {
        stage('Release to Production') {
     steps {
         echo "Merging changes to production branch..."
-        sh '''
-            git checkout production
-            git fetch origin
-            git pull origin production --rebase
-            git merge main
-            git push origin production
-        '''
-        echo "Releasing the website to production..."
-        sh 'echo "Release to production completed."'
     }
 }
-
-
 
         stage('Monitoring and Alerting') {
             steps {
@@ -82,18 +71,21 @@ pipeline {
             }
         }
     }
-    post {
-        always {
-            echo 'Cleaning up...'
-            sh '''
-                pkill -f "node ./website" || true
-            '''
+post {
+    always {
+        script {
+            node {
+                echo 'Cleaning up...'
+                sh '''
+                    pkill -f "node ./website" || true
+                '''
+            }
         }
-        success {
-            echo 'Pipeline completed successfully!'
-        }
-        failure {
-            echo 'Pipeline failed'
-        }
+    }
+    success {
+        echo 'Pipeline completed successfully!'
+    }
+    failure {
+        echo 'Pipeline failed'
     }
 }
